version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8280:8080
      - 50000:50000
    container_name: jenkins
    restart: always
    volumes:
      - /opt/jenkins-training/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

  server:
    image: server-deb12-dckr:project
#    restart: always
    privileged: true
    user: root
    container_name: project-server-deb-dckr
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - jenkins
    ports:
      - "3000:3000"
      - "2222:22"
      - "10017:10017"
      - "20017:20017"
    tty: true
#    command: --
    volumes:
      - /opt/jenkins-training/jenkins_compose/data_server:/var/jenkins_home
    restart: always             # run as a service
