---
# [serveur_debian_test]
# conteneur_test ansible_connection=docker ansible_user=root
all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'


prod:
  hosts:
    serveur_debian_test:
      ansible_host: conteneur_test
      ansible_connection: docker
      ansible_user: root
